### ISSUE TITLE
An efficient library for symmetric pairing Python

### ISSUE THREAD

**Issue by Loryerba** [dfaranha/OpenPairing#1]
Hi, sorry do you know any library about symmetric pairing and cyclic group in Python? I need to implement the Catalano and Fiore Vector Commitments.

Thanks

**Comment by dfaranha** [comment]
Symmetric pairings are really out of fashion, but Charm should support the old PBC library that had such pairings.

Isn't there a Type-3 version of the protocol you can use?

**Comment by Loryerba** [comment]
I solved by using ecpy on Python but still get two different pairings when i have to get the same result ;(

**Comment by dfaranha** [comment]
I suggest getting help from the authors of ecpy. :)
